import "TalentCls.idl";
#include <Collection.h>

namespace SENG3110_Project
{
	runtimeclass TalentViewModel
	{
		TalentViewModel();
		SENG3110_Project.TalentCls DefaultTalent{ get; };
		Windows.Foundation.Collections.IVector<IInspectable> Talents{ get; };
	}
}